using System.Text;

namespace Quiver.SourceGen;

internal static class GraphRelationshipEmitter
{
    private static readonly Dictionary<string, (string write, string read)> _typeMap = new()
    {
        ["string"]  = ("PropertyValue.FromString(entity.{0})", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["string?"] = ("PropertyValue.FromString(entity.{0} ?? \"\")", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["int"]     = ("PropertyValue.FromInt32(entity.{0})", "tx.GetProperty(id, \"{1}\").Int32Value"),
        ["long"]    = ("PropertyValue.FromInt64(entity.{0})", "tx.GetProperty(id, \"{1}\").Int64Value"),
        ["double"]  = ("PropertyValue.FromDouble(entity.{0})", "tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["float"]   = ("PropertyValue.FromDouble((double)entity.{0})", "(float)tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["Half"]    = ("PropertyValue.FromDouble((double)entity.{0})", "(System.Half)tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["bool"]    = ("PropertyValue.FromBool(entity.{0})", "tx.GetProperty(id, \"{1}\").BoolValue"),
        // FT-35 (増分2): 日時系は Int64 (Ticks/DayNumber) に正準化して格納。TimeZone 契約は TemporalCodec。
        ["DateTime"]       = ("PropertyValue.FromDateTime(entity.{0})", "tx.GetProperty(id, \"{1}\").DateTimeValue"),
        ["DateTimeOffset"] = ("PropertyValue.FromDateTimeOffset(entity.{0})", "tx.GetProperty(id, \"{1}\").DateTimeOffsetValue"),
        ["DateOnly"]       = ("PropertyValue.FromDateOnly(entity.{0})", "tx.GetProperty(id, \"{1}\").DateOnlyValue"),
        ["TimeOnly"]       = ("PropertyValue.FromTimeOnly(entity.{0})", "tx.GetProperty(id, \"{1}\").TimeOnlyValue"),
        ["TimeSpan"]       = ("PropertyValue.FromTimeSpan(entity.{0})", "tx.GetProperty(id, \"{1}\").TimeSpanValue"),
    };

    public static string Emit(GraphRelationshipModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Quiver;");
        sb.AppendLine("using Quiver.Api;");
        sb.AppendLine("using Quiver.Core;");
        sb.AppendLine("using Quiver.Storage.Records;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.ClassName} : Quiver.Api.IGraphRelationship<{model.ClassName}, {model.SourceFqn}, {model.TargetFqn}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string GraphType => \"{model.RelType}\";");
        sb.AppendLine();

        // Insert
        sb.AppendLine($"    public static Quiver.Core.RelationshipId Insert(IGraphTransaction tx, Quiver.Core.NodeId from, Quiver.Core.NodeId to, {model.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var id = tx.CreateRelationship(from, to, \"{model.RelType}\");");
        foreach (var prop in model.Properties)
            EmitSetProperty(sb, prop);
        sb.AppendLine("        return id;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Load
        sb.AppendLine($"    public static {model.ClassName} Load(IGraphTransaction tx, Quiver.Core.RelationshipId id)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.ClassName}");
        sb.AppendLine("        {");
        foreach (var prop in model.Properties)
        {
            if (_typeMap.TryGetValue(prop.CSharpType, out var map))
                sb.AppendLine($"            {prop.PropertyName} = {string.Format(map.read, prop.PropertyName, prop.GraphKey)},");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Update
        sb.AppendLine($"    public static void Update(IGraphTransaction tx, Quiver.Core.RelationshipId id, {model.ClassName} entity)");
        sb.AppendLine("    {");
        foreach (var prop in model.Properties)
            EmitSetProperty(sb, prop);
        sb.AppendLine("    }");
        sb.AppendLine();

        // Delete
        sb.AppendLine($"    public static void Delete(IGraphTransaction tx, Quiver.Core.RelationshipId id) => tx.DeleteRelationship(id);");

        sb.AppendLine("}");
        sb.AppendLine();

        // Hop 型保存トラバーサル糖衣 (ARCH-8): g.Nodes<Source>().<RelType>() が
        // TypedGraphTraversal<Target> を返す。型安全な Out<TRel, TTarget>() を被せる薄い拡張。
        sb.AppendLine($"/// <summary>{model.ClassName} (型保存トラバーサル糖衣) — SourceGenerator 生成。</summary>");
        sb.AppendLine($"public static class {model.ClassName}TraversalExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>{model.SourceFqn} から {model.RelType} を外向に辿り、{model.TargetFqn} 型を保存する。</summary>");
        sb.AppendLine($"    public static Quiver.Api.TypedGraphTraversal<{model.TargetFqn}> {model.ClassName}(this Quiver.Api.TypedGraphTraversal<{model.SourceFqn}> source)");
        sb.AppendLine($"        => source.Out<{model.ClassName}, {model.TargetFqn}>();");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>GC-8: {model.RelType} エッジを式ツリー述語で絞り込んでから {model.TargetFqn} 型を保存して辿る。</summary>");
        sb.AppendLine($"    public static Quiver.Api.TypedGraphTraversal<{model.TargetFqn}> {model.ClassName}(this Quiver.Api.TypedGraphTraversal<{model.SourceFqn}> source, System.Linq.Expressions.Expression<System.Func<{model.ClassName}, bool>> edgeFilter)");
        sb.AppendLine($"        => source.OutWhere<{model.ClassName}, {model.TargetFqn}>(edgeFilter);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSetProperty(StringBuilder sb, PropertyModel prop)
    {
        if (!_typeMap.TryGetValue(prop.CSharpType, out var map)) return;
        var writeExpr = string.Format(map.write, prop.PropertyName, prop.GraphKey);
        sb.AppendLine($"        tx.SetProperty(id, \"{prop.GraphKey}\", {writeExpr});");
    }
}
