using System.Text;

namespace Quiver.SourceGen;

internal static class GraphNexusEmitter
{
    // Nexusのプロパティは header 直後の inline property store に置かれるため、
    // vertex / edge と同じスカラー変換表を使う。
    private static readonly Dictionary<string, (string write, string read)> _typeMap = new()
    {
        ["string"]  = ("PropertyValue.FromString(entity.{0})", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["string?"] = ("PropertyValue.FromString(entity.{0} ?? \"\")", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["int"]     = ("PropertyValue.FromInt32(entity.{0})", "tx.GetProperty(id, \"{1}\").Int32Value"),
        ["long"]    = ("PropertyValue.FromInt64(entity.{0})", "tx.GetProperty(id, \"{1}\").Int64Value"),
        ["double"]  = ("PropertyValue.FromDouble(entity.{0})", "tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["float"]   = ("PropertyValue.FromDouble((double)entity.{0})", "(float)tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["Half"]    = ("PropertyValue.FromDouble((double)entity.{0})", "(System.Half)tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["bool"]    = ("PropertyValue.FromBool(entity.{0})", "tx.GetProperty(id, \"{1}\").BoolValue"),
        ["DateTime"]       = ("PropertyValue.FromDateTime(entity.{0})", "tx.GetProperty(id, \"{1}\").DateTimeValue"),
        ["DateTimeOffset"] = ("PropertyValue.FromDateTimeOffset(entity.{0})", "tx.GetProperty(id, \"{1}\").DateTimeOffsetValue"),
        ["DateOnly"]       = ("PropertyValue.FromDateOnly(entity.{0})", "tx.GetProperty(id, \"{1}\").DateOnlyValue"),
        ["TimeOnly"]       = ("PropertyValue.FromTimeOnly(entity.{0})", "tx.GetProperty(id, \"{1}\").TimeOnlyValue"),
        ["TimeSpan"]       = ("PropertyValue.FromTimeSpan(entity.{0})", "tx.GetProperty(id, \"{1}\").TimeSpanValue"),
    };

    private static readonly Dictionary<string, string> _mvWriteExpr = new()
    {
        ["string"]  = "PropertyValue.FromString(__v)",
        ["int"]     = "PropertyValue.FromInt32(__v)",
        ["long"]    = "PropertyValue.FromInt64(__v)",
        ["double"]  = "PropertyValue.FromDouble(__v)",
        ["float"]   = "PropertyValue.FromDouble((double)__v)",
        ["Half"]    = "PropertyValue.FromDouble((double)__v)",
        ["bool"]    = "PropertyValue.FromBool(__v)",
        ["DateTime"]       = "PropertyValue.FromDateTime(__v)",
        ["DateTimeOffset"] = "PropertyValue.FromDateTimeOffset(__v)",
        ["DateOnly"]       = "PropertyValue.FromDateOnly(__v)",
        ["TimeOnly"]       = "PropertyValue.FromTimeOnly(__v)",
        ["TimeSpan"]       = "PropertyValue.FromTimeSpan(__v)",
    };

    private static readonly Dictionary<string, string> _mvReadExpr = new()
    {
        ["string"]  = "System.Text.Encoding.UTF8.GetString(__e.Current.Utf8StringValue)",
        ["int"]     = "__e.Current.Int32Value",
        ["long"]    = "__e.Current.Int64Value",
        ["double"]  = "__e.Current.DoubleValue",
        ["float"]   = "(float)__e.Current.DoubleValue",
        ["Half"]    = "(System.Half)__e.Current.DoubleValue",
        ["bool"]    = "__e.Current.BoolValue",
        ["DateTime"]       = "__e.Current.DateTimeValue",
        ["DateTimeOffset"] = "__e.Current.DateTimeOffsetValue",
        ["DateOnly"]       = "__e.Current.DateOnlyValue",
        ["TimeOnly"]       = "__e.Current.TimeOnlyValue",
        ["TimeSpan"]       = "__e.Current.TimeSpanValue",
    };

    public static string Emit(GraphNexusModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Quiver;");
        sb.AppendLine("using Quiver.Api;");
        sb.AppendLine("using Quiver.Core;");
        sb.AppendLine("using Quiver.Storage.Records;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var multiValueProps = model.Properties.FindAll(p => p.IsMultiValued);

        sb.AppendLine($"partial class {model.ClassName} : Quiver.Api.IGraphNexus<{model.ClassName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string GraphType => \"{model.NexusType}\";");
        sb.AppendLine();

        EmitInsert(sb, model);
        EmitLoad(sb, model, multiValueProps);
        EmitUpdate(sb, model);
        EmitReplace(sb, model);

        sb.AppendLine($"    public static void Delete(IWriteTransaction tx, Quiver.Core.NexusId id) => tx.DeleteNexus(id);");
        sb.AppendLine("}");

        if (model.Roles.Count > 0)
        {
            sb.AppendLine();
            EmitTraversalExtensions(sb, model);
        }

        return sb.ToString();
    }

    /// <summary>
    /// ロールごとの型保存トラバーサル糖衣を emit する。ロール名とNexus型は
    /// 生成時にリテラルで畳み込み、実行は型なし DSL と同じ論理オペレータへ委譲する。
    /// </summary>
    private static void EmitTraversalExtensions(StringBuilder sb, GraphNexusModel model)
    {
        // 拡張クラスはシグネチャに付与クラス型を含むため、アクセシビリティを揃える。
        var access = model.IsPublic ? "public" : "internal";
        var he = model.ClassName;

        sb.AppendLine($"/// <summary>{he} (型保存トラバーサル糖衣) — SourceGenerator 生成。</summary>");
        sb.AppendLine($"{access} static class {he}TraversalExtensions");
        sb.AppendLine("{");
        bool first = true;
        foreach (var role in model.Roles)
        {
            if (!first) sb.AppendLine();
            first = false;
            var vertex = role.VertexFqn;

            // vertex → nexus: Vertexが当該ロールで参加するNexusへ展開する。
            sb.AppendLine($"    /// <summary>現在のVertexが {role.RoleName} ロールで参加する {model.NexusType} Nexusへ展開し、{he} 型を保存する。</summary>");
            sb.AppendLine($"    public static Quiver.Api.TypedGraphNexusTraversal<{he}> {he}As{role.PropertyName}(this Quiver.Api.TypedGraphTraversal<{vertex}> source)");
            sb.AppendLine($"        => source.Nexuses<{he}>(\"{role.RoleName}\");");
            sb.AppendLine();

            // nexus → members: 複数メンバーロールでも各メンバーを個別の行として放出する。
            sb.AppendLine($"    /// <summary>{role.RoleName} ロールのメンバーVertexへ展開し、Vertex型を保存する。複数メンバーは個別の行として放出する。</summary>");
            sb.AppendLine($"    public static Quiver.Api.TypedGraphTraversal<{vertex}> {role.PropertyName}(this Quiver.Api.TypedGraphNexusTraversal<{he}> source)");
            sb.AppendLine($"        => source.MembersOf<{vertex}>(\"{role.RoleName}\");");
            sb.AppendLine();

            // co-membership: 到達起点Vertexを除いた同ロールのメンバーへ展開する。
            sb.AppendLine($"    /// <summary>{role.RoleName} ロールのメンバーから、このNexusへ到達した起点Vertexを除いて展開し、Vertex型を保存する。</summary>");
            sb.AppendLine($"    public static Quiver.Api.TypedGraphTraversal<{vertex}> Other{role.PropertyName}(this Quiver.Api.TypedGraphNexusTraversal<{he}> source)");
            sb.AppendLine($"        => source.OtherMembersOf<{vertex}>(\"{role.RoleName}\");");
        }
        sb.AppendLine("}");
    }

    private static void EmitInsert(StringBuilder sb, GraphNexusModel model)
    {
        sb.AppendLine($"    public static Quiver.Core.NexusId Insert(IWriteTransaction tx, {model.ClassName} entity)");
        sb.AppendLine("    {");
        // NexusMember は managed 型 (Role が string) のため stackalloc できない。
        // 全メンバーを一度組み立てて CreateNexus を一回だけ呼ぶ。
        sb.AppendLine("        var __members = new System.Collections.Generic.List<Quiver.NexusMember>();");
        foreach (var role in model.Roles)
        {
            if (role.IsMultiValued)
            {
                sb.AppendLine($"        if (entity.{role.PropertyName} != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            foreach (var __r in entity.{role.PropertyName})");
                sb.AppendLine($"                __members.Add(new Quiver.NexusMember(\"{role.RoleName}\", __r.VertexId));");
                sb.AppendLine("        }");
            }
            else if (role.IsOptional)
            {
                sb.AppendLine($"        if (entity.{role.PropertyName} is {{ }} __{role.PropertyName})");
                sb.AppendLine($"            __members.Add(new Quiver.NexusMember(\"{role.RoleName}\", __{role.PropertyName}.VertexId));");
            }
            else
            {
                sb.AppendLine($"        __members.Add(new Quiver.NexusMember(\"{role.RoleName}\", entity.{role.PropertyName}.VertexId));");
            }
        }
        sb.AppendLine($"        var id = tx.CreateNexus(\"{model.NexusType}\", System.Runtime.InteropServices.CollectionsMarshal.AsSpan(__members));");
        foreach (var prop in model.Properties)
        {
            if (prop.IsMultiValued)
                EmitInsertMultiValue(sb, prop);
            else
                EmitSetProperty(sb, prop);
        }
        sb.AppendLine("        return id;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitLoad(StringBuilder sb, GraphNexusModel model, List<PropertyModel> multiValueProps)
    {
        sb.AppendLine($"    public static {model.ClassName} Load(IReadTransaction tx, Quiver.Core.NexusId id)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __entity = new {model.ClassName}");
        sb.AppendLine("        {");
        foreach (var prop in model.Properties)
        {
            if (!prop.IsMultiValued && _typeMap.TryGetValue(prop.CSharpType, out var map))
                sb.AppendLine($"            {prop.PropertyName} = {string.Format(map.read, prop.PropertyName, prop.GraphKey)},");
        }
        sb.AppendLine("        };");

        // ロール束縛はプロパティとは別の責務として、メンバー列挙から復元する。
        foreach (var role in model.Roles)
            EmitLoadRole(sb, role);

        foreach (var prop in multiValueProps)
            EmitLoadMultiValue(sb, prop);

        sb.AppendLine("        return __entity;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitLoadRole(StringBuilder sb, RoleModel role)
    {
        if (role.IsMultiValued)
        {
            sb.AppendLine("        {");
            sb.AppendLine($"            var __list = new System.Collections.Generic.List<Quiver.Api.GraphVertexRef<{role.VertexFqn}>>();");
            sb.AppendLine($"            var __m = tx.GetMembers(id, \"{role.RoleName}\");");
            sb.AppendLine("            while (__m.MoveNext())");
            sb.AppendLine($"                __list.Add(new Quiver.Api.GraphVertexRef<{role.VertexFqn}>(__m.Current.VertexId));");
            sb.AppendLine("            __m.Dispose();");
            sb.AppendLine($"            __entity.{role.PropertyName} = __list;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        {");
            sb.AppendLine($"            var __m = tx.GetMembers(id, \"{role.RoleName}\");");
            sb.AppendLine("            if (__m.MoveNext())");
            sb.AppendLine($"                __entity.{role.PropertyName} = new Quiver.Api.GraphVertexRef<{role.VertexFqn}>(__m.Current.VertexId);");
            sb.AppendLine("            __m.Dispose();");
            sb.AppendLine("        }");
        }
    }

    private static void EmitUpdate(StringBuilder sb, GraphNexusModel model)
    {
        // メンバー集合は作成時不変 — Update はプロパティのみを書き、ロール束縛は再構成しない。
        sb.AppendLine($"    public static void Update(IWriteTransaction tx, Quiver.Core.NexusId id, {model.ClassName} entity)");
        sb.AppendLine("    {");
        foreach (var prop in model.Properties)
        {
            if (prop.IsMultiValued)
                EmitUpdateMultiValue(sb, prop);
            else
                EmitSetProperty(sb, prop);
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitReplace(StringBuilder sb, GraphNexusModel model)
    {
        sb.AppendLine($"    public static Quiver.NexusReplacement Replace(IWriteTransaction tx, Quiver.Core.NexusId id, {model.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __members = new System.Collections.Generic.List<Quiver.NexusMember>();");
        foreach (var role in model.Roles)
        {
            if (role.IsMultiValued)
            {
                sb.AppendLine($"        if (entity.{role.PropertyName} != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            foreach (var __r in entity.{role.PropertyName})");
                sb.AppendLine($"                __members.Add(new Quiver.NexusMember(\"{role.RoleName}\", __r.VertexId));");
                sb.AppendLine("        }");
            }
            else if (role.IsOptional)
            {
                sb.AppendLine($"        if (entity.{role.PropertyName} is {{ }} __{role.PropertyName})");
                sb.AppendLine($"            __members.Add(new Quiver.NexusMember(\"{role.RoleName}\", __{role.PropertyName}.VertexId));");
            }
            else
            {
                sb.AppendLine($"        __members.Add(new Quiver.NexusMember(\"{role.RoleName}\", entity.{role.PropertyName}.VertexId));");
            }
        }
        sb.AppendLine($"        var __replacement = tx.ReplaceNexus(id, \"{model.NexusType}\", System.Runtime.InteropServices.CollectionsMarshal.AsSpan(__members));");
        sb.AppendLine("        Update(tx, __replacement.NewId, entity);");
        sb.AppendLine("        return __replacement;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitSetProperty(StringBuilder sb, PropertyModel prop)
    {
        if (!_typeMap.TryGetValue(prop.CSharpType, out var map)) return;
        var writeExpr = string.Format(map.write, prop.PropertyName, prop.GraphKey);
        sb.AppendLine($"        tx.SetProperty(id, \"{prop.GraphKey}\", {writeExpr});");
    }

    private static void EmitInsertMultiValue(StringBuilder sb, PropertyModel prop)
    {
        if (!_mvWriteExpr.TryGetValue(prop.CSharpType, out var writeExpr)) return;
        sb.AppendLine($"        if (entity.{prop.PropertyName} != null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            foreach (var __v in entity.{prop.PropertyName})");
        sb.AppendLine($"                tx.AddPropertyValue(id, \"{prop.GraphKey}\", {writeExpr});");
        sb.AppendLine("        }");
    }

    private static void EmitLoadMultiValue(StringBuilder sb, PropertyModel prop)
    {
        if (!_mvReadExpr.TryGetValue(prop.CSharpType, out var readExpr)) return;
        sb.AppendLine("        {");
        sb.AppendLine($"            var __list = new System.Collections.Generic.List<{prop.CSharpType}>();");
        sb.AppendLine($"            var __e = tx.GetPropertyValues(id, \"{prop.GraphKey}\");");
        sb.AppendLine("            while (__e.MoveNext())");
        sb.AppendLine($"                __list.Add({readExpr});");
        sb.AppendLine("            __e.Dispose();");
        sb.AppendLine($"            __entity.{prop.PropertyName} = __list;");
        sb.AppendLine("        }");
    }

    private static void EmitUpdateMultiValue(StringBuilder sb, PropertyModel prop)
    {
        if (!_mvWriteExpr.TryGetValue(prop.CSharpType, out var writeExpr)) return;
        if (!_mvReadExpr.TryGetValue(prop.CSharpType, out var readExpr)) return;
        sb.AppendLine("        {");
        sb.AppendLine($"            var __old = new System.Collections.Generic.HashSet<{prop.CSharpType}>();");
        sb.AppendLine($"            var __e = tx.GetPropertyValues(id, \"{prop.GraphKey}\");");
        sb.AppendLine("            while (__e.MoveNext())");
        sb.AppendLine($"                __old.Add({readExpr});");
        sb.AppendLine("            __e.Dispose();");
        sb.AppendLine($"            if (entity.{prop.PropertyName} != null)");
        sb.AppendLine("            {");
        sb.AppendLine($"                foreach (var __v in entity.{prop.PropertyName})");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (!__old.Remove(__v))");
        sb.AppendLine($"                        tx.AddPropertyValue(id, \"{prop.GraphKey}\", {writeExpr});");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine($"            foreach (var __v in __old)");
        sb.AppendLine($"                tx.RemovePropertyValue(id, \"{prop.GraphKey}\", {writeExpr});");
        sb.AppendLine("        }");
    }
}
