using System.Text;

namespace Quiver.SourceGen;

internal static class GraphRelationshipEmitter
{
    private static readonly Dictionary<string, (string write, string read)> _typeMap = new()
    {
        ["string"]  = ("PropertyValue.FromString(entity.{0})", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["string?"] = ("PropertyValue.FromString(entity.{0} ?? \"\")", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["int"]     = ("PropertyValue.FromInt32(entity.{0})", "tx.GetProperty(id, \"{1}\").Int32Value"),
        ["long"]    = ("PropertyValue.FromInt64(entity.{0})", "tx.GetProperty(id, \"{1}\").Int64Value"),
        ["double"]  = ("PropertyValue.FromDouble(entity.{0})", "tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["bool"]    = ("PropertyValue.FromBool(entity.{0})", "tx.GetProperty(id, \"{1}\").BoolValue"),
    };

    public static string Emit(GraphRelationshipModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Quiver;");
        sb.AppendLine("using Quiver.Client;");
        sb.AppendLine("using Quiver.Core;");
        sb.AppendLine("using Quiver.Stores;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.ClassName} : Quiver.Client.IGraphRelationship<{model.ClassName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string GraphType => \"{model.RelType}\";");
        sb.AppendLine();

        // Insert
        sb.AppendLine($"    public static Quiver.Core.RelationshipId Insert(IGraphTransaction tx, Quiver.Core.NodeId from, Quiver.Core.NodeId to, {model.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var id = tx.CreateRelationship(from, to, \"{model.RelType}\");");
        foreach (var prop in model.Properties)
            EmitSetProperty(sb, prop);
        sb.AppendLine("        return id;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Load
        sb.AppendLine($"    public static {model.ClassName} Load(IGraphTransaction tx, Quiver.Core.RelationshipId id)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.ClassName}");
        sb.AppendLine("        {");
        foreach (var prop in model.Properties)
        {
            if (_typeMap.TryGetValue(prop.CSharpType, out var map))
                sb.AppendLine($"            {prop.PropertyName} = {string.Format(map.read, prop.PropertyName, prop.GraphKey)},");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Update
        sb.AppendLine($"    public static void Update(IGraphTransaction tx, Quiver.Core.RelationshipId id, {model.ClassName} entity)");
        sb.AppendLine("    {");
        foreach (var prop in model.Properties)
            EmitSetProperty(sb, prop);
        sb.AppendLine("    }");
        sb.AppendLine();

        // Delete
        sb.AppendLine($"    public static void Delete(IGraphTransaction tx, Quiver.Core.RelationshipId id) => tx.DeleteRelationship(id);");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSetProperty(StringBuilder sb, PropertyModel prop)
    {
        if (!_typeMap.TryGetValue(prop.CSharpType, out var map)) return;
        var writeExpr = string.Format(map.write, prop.PropertyName, prop.GraphKey);
        sb.AppendLine($"        tx.SetProperty(id, \"{prop.GraphKey}\", {writeExpr});");
    }
}
