using System.Text;

namespace Quiver.SourceGen;

internal static class GraphEdgeEmitter
{
    private static readonly Dictionary<string, (string write, string read)> _typeMap = new()
    {
        ["string"]  = ("PropertyValue.FromString(entity.{0})", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["string?"] = ("PropertyValue.FromString(entity.{0} ?? \"\")", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["int"]     = ("PropertyValue.FromInt32(entity.{0})", "tx.GetProperty(id, \"{1}\").Int32Value"),
        ["long"]    = ("PropertyValue.FromInt64(entity.{0})", "tx.GetProperty(id, \"{1}\").Int64Value"),
        ["double"]  = ("PropertyValue.FromDouble(entity.{0})", "tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["float"]   = ("PropertyValue.FromDouble((double)entity.{0})", "(float)tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["Half"]    = ("PropertyValue.FromDouble((double)entity.{0})", "(System.Half)tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["bool"]    = ("PropertyValue.FromBool(entity.{0})", "tx.GetProperty(id, \"{1}\").BoolValue"),
        ["DateTime"]       = ("PropertyValue.FromDateTime(entity.{0})", "tx.GetProperty(id, \"{1}\").DateTimeValue"),
        ["DateTimeOffset"] = ("PropertyValue.FromDateTimeOffset(entity.{0})", "tx.GetProperty(id, \"{1}\").DateTimeOffsetValue"),
        ["DateOnly"]       = ("PropertyValue.FromDateOnly(entity.{0})", "tx.GetProperty(id, \"{1}\").DateOnlyValue"),
        ["TimeOnly"]       = ("PropertyValue.FromTimeOnly(entity.{0})", "tx.GetProperty(id, \"{1}\").TimeOnlyValue"),
        ["TimeSpan"]       = ("PropertyValue.FromTimeSpan(entity.{0})", "tx.GetProperty(id, \"{1}\").TimeSpanValue"),
    };

    private static readonly Dictionary<string, string> _mvWriteExpr = new()
    {
        ["string"]  = "PropertyValue.FromString(__v)",
        ["int"]     = "PropertyValue.FromInt32(__v)",
        ["long"]    = "PropertyValue.FromInt64(__v)",
        ["double"]  = "PropertyValue.FromDouble(__v)",
        ["float"]   = "PropertyValue.FromDouble((double)__v)",
        ["Half"]    = "PropertyValue.FromDouble((double)__v)",
        ["bool"]    = "PropertyValue.FromBool(__v)",
        ["DateTime"]       = "PropertyValue.FromDateTime(__v)",
        ["DateTimeOffset"] = "PropertyValue.FromDateTimeOffset(__v)",
        ["DateOnly"]       = "PropertyValue.FromDateOnly(__v)",
        ["TimeOnly"]       = "PropertyValue.FromTimeOnly(__v)",
        ["TimeSpan"]       = "PropertyValue.FromTimeSpan(__v)",
    };

    private static readonly Dictionary<string, string> _mvReadExpr = new()
    {
        ["string"]  = "System.Text.Encoding.UTF8.GetString(__e.Current.Utf8StringValue)",
        ["int"]     = "__e.Current.Int32Value",
        ["long"]    = "__e.Current.Int64Value",
        ["double"]  = "__e.Current.DoubleValue",
        ["float"]   = "(float)__e.Current.DoubleValue",
        ["Half"]    = "(System.Half)__e.Current.DoubleValue",
        ["bool"]    = "__e.Current.BoolValue",
        ["DateTime"]       = "__e.Current.DateTimeValue",
        ["DateTimeOffset"] = "__e.Current.DateTimeOffsetValue",
        ["DateOnly"]       = "__e.Current.DateOnlyValue",
        ["TimeOnly"]       = "__e.Current.TimeOnlyValue",
        ["TimeSpan"]       = "__e.Current.TimeSpanValue",
    };

    public static string Emit(GraphEdgeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Quiver;");
        sb.AppendLine("using Quiver.Api;");
        sb.AppendLine("using Quiver.Core;");
        sb.AppendLine("using Quiver.Storage.Records;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var multiValueProps = model.Properties.FindAll(p => p.IsMultiValued);

        sb.AppendLine($"partial class {model.ClassName} : Quiver.Api.IGraphEdge<{model.ClassName}, {model.SourceFqn}, {model.TargetFqn}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string GraphType => \"{model.EdgeType}\";");
        sb.AppendLine();

        // 挿入
        sb.AppendLine($"    public static Quiver.Core.EdgeId Insert(IGraphTransaction tx, Quiver.Core.VertexId from, Quiver.Core.VertexId to, {model.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var id = tx.CreateEdge(from, to, \"{model.EdgeType}\");");
        foreach (var prop in model.Properties)
        {
            if (prop.IsMultiValued)
                EmitInsertMultiValue(sb, prop);
            else
                EmitSetProperty(sb, prop);
        }
        sb.AppendLine("        return id;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 読み込み
        sb.AppendLine($"    public static {model.ClassName} Load(IGraphTransaction tx, Quiver.Core.EdgeId id)");
        sb.AppendLine("    {");
        if (multiValueProps.Count > 0)
        {
            sb.AppendLine($"        var __entity = new {model.ClassName}");
            sb.AppendLine("        {");
            foreach (var prop in model.Properties)
            {
                if (!prop.IsMultiValued && _typeMap.TryGetValue(prop.CSharpType, out var map))
                    sb.AppendLine($"            {prop.PropertyName} = {string.Format(map.read, prop.PropertyName, prop.GraphKey)},");
            }
            sb.AppendLine("        };");
            foreach (var prop in multiValueProps)
                EmitLoadMultiValue(sb, prop);
            sb.AppendLine("        return __entity;");
        }
        else
        {
            sb.AppendLine($"        return new {model.ClassName}");
            sb.AppendLine("        {");
            foreach (var prop in model.Properties)
            {
                if (_typeMap.TryGetValue(prop.CSharpType, out var map))
                    sb.AppendLine($"            {prop.PropertyName} = {string.Format(map.read, prop.PropertyName, prop.GraphKey)},");
            }
            sb.AppendLine("        };");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // 更新
        sb.AppendLine($"    public static void Update(IGraphTransaction tx, Quiver.Core.EdgeId id, {model.ClassName} entity)");
        sb.AppendLine("    {");
        foreach (var prop in model.Properties)
        {
            if (prop.IsMultiValued)
                EmitUpdateMultiValue(sb, prop);
            else
                EmitSetProperty(sb, prop);
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // 削除
        sb.AppendLine($"    public static void Delete(IGraphTransaction tx, Quiver.Core.EdgeId id) => tx.DeleteEdge(id);");

        sb.AppendLine("}");
        sb.AppendLine();

        // ホップ後の型を保存するトラバーサル糖衣
        sb.AppendLine($"/// <summary>{model.ClassName} (型保存トラバーサル糖衣) — SourceGenerator 生成。</summary>");
        sb.AppendLine($"public static class {model.ClassName}TraversalExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>{model.SourceFqn} から {model.EdgeType} を外向に辿り、{model.TargetFqn} 型を保存する。</summary>");
        sb.AppendLine($"    public static Quiver.Api.TypedGraphTraversal<{model.TargetFqn}> {model.ClassName}(this Quiver.Api.TypedGraphTraversal<{model.SourceFqn}> source)");
        sb.AppendLine($"        => source.Out<{model.ClassName}, {model.TargetFqn}>();");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>{model.EdgeType} エッジを式ツリー述語で絞り込んでから {model.TargetFqn} 型を保存して辿る。</summary>");
        sb.AppendLine($"    public static Quiver.Api.TypedGraphTraversal<{model.TargetFqn}> {model.ClassName}(this Quiver.Api.TypedGraphTraversal<{model.SourceFqn}> source, System.Linq.Expressions.Expression<System.Func<{model.ClassName}, bool>> edgeFilter)");
        sb.AppendLine($"        => source.OutWhere<{model.ClassName}, {model.TargetFqn}>(edgeFilter);");
        sb.AppendLine();

        // 書き込み終端の糖衣
        var s = model.SourceFqn;
        var t = model.TargetFqn;
        var r = model.ClassName;

        sb.AppendLine($"    /// <summary>{s} と {t} の直積に {model.EdgeType} 辺を生成する。</summary>");
        sb.AppendLine($"    public static long Add{r}(this Quiver.Api.TypedGraphTraversal<{s}> sources, Quiver.Api.TypedGraphTraversal<{t}> targets)");
        sb.AppendLine($"        => Quiver.Api.TypedGraphTraversalWriteExtensions.AddEdge<{s}, {r}, {t}>(sources, targets);");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>始点ごとに終点を求め {model.EdgeType} 辺を生成する (相関版)。</summary>");
        sb.AppendLine($"    public static long Add{r}(this Quiver.Api.TypedGraphTraversal<{s}> sources, System.Func<{s}, Quiver.Api.TypedGraphTraversal<{t}>> targets)");
        sb.AppendLine($"        => Quiver.Api.TypedGraphTraversalWriteExtensions.AddEdge<{s}, {r}, {t}>(sources, targets);");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>{s} と {t} の直積で {model.EdgeType} 辺を upsert する。</summary>");
        sb.AppendLine($"    public static (long Created, long Matched) Merge{r}(this Quiver.Api.TypedGraphTraversal<{s}> sources, Quiver.Api.TypedGraphTraversal<{t}> targets)");
        sb.AppendLine($"        => Quiver.Api.TypedGraphTraversalWriteExtensions.MergeEdge<{s}, {r}, {t}>(sources, targets);");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>始点ごとに終点を求め {model.EdgeType} 辺を upsert する (相関版)。</summary>");
        sb.AppendLine($"    public static (long Created, long Matched) Merge{r}(this Quiver.Api.TypedGraphTraversal<{s}> sources, System.Func<{s}, Quiver.Api.TypedGraphTraversal<{t}>> targets)");
        sb.AppendLine($"        => Quiver.Api.TypedGraphTraversalWriteExtensions.MergeEdge<{s}, {r}, {t}>(sources, targets);");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSetProperty(StringBuilder sb, PropertyModel prop)
    {
        if (!_typeMap.TryGetValue(prop.CSharpType, out var map)) return;
        var writeExpr = string.Format(map.write, prop.PropertyName, prop.GraphKey);
        sb.AppendLine($"        tx.SetProperty(id, \"{prop.GraphKey}\", {writeExpr});");
    }

    private static void EmitInsertMultiValue(StringBuilder sb, PropertyModel prop)
    {
        if (!_mvWriteExpr.TryGetValue(prop.CSharpType, out var writeExpr)) return;
        sb.AppendLine($"        if (entity.{prop.PropertyName} != null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            foreach (var __v in entity.{prop.PropertyName})");
        sb.AppendLine($"                tx.AddPropertyValue(id, \"{prop.GraphKey}\", {writeExpr});");
        sb.AppendLine("        }");
    }

    private static void EmitLoadMultiValue(StringBuilder sb, PropertyModel prop)
    {
        if (!_mvReadExpr.TryGetValue(prop.CSharpType, out var readExpr)) return;
        sb.AppendLine("        {");
        sb.AppendLine($"            var __list = new System.Collections.Generic.List<{prop.CSharpType}>();");
        sb.AppendLine($"            var __e = tx.GetPropertyValues(id, \"{prop.GraphKey}\");");
        sb.AppendLine("            while (__e.MoveNext())");
        sb.AppendLine($"                __list.Add({readExpr});");
        sb.AppendLine("            __e.Dispose();");
        sb.AppendLine($"            __entity.{prop.PropertyName} = __list;");
        sb.AppendLine("        }");
    }

    private static void EmitUpdateMultiValue(StringBuilder sb, PropertyModel prop)
    {
        if (!_mvWriteExpr.TryGetValue(prop.CSharpType, out var writeExpr)) return;
        if (!_mvReadExpr.TryGetValue(prop.CSharpType, out var readExpr)) return;
        sb.AppendLine("        {");
        sb.AppendLine($"            var __old = new System.Collections.Generic.HashSet<{prop.CSharpType}>();");
        sb.AppendLine($"            var __e = tx.GetPropertyValues(id, \"{prop.GraphKey}\");");
        sb.AppendLine("            while (__e.MoveNext())");
        sb.AppendLine($"                __old.Add({readExpr});");
        sb.AppendLine("            __e.Dispose();");
        sb.AppendLine($"            if (entity.{prop.PropertyName} != null)");
        sb.AppendLine("            {");
        sb.AppendLine($"                foreach (var __v in entity.{prop.PropertyName})");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (!__old.Remove(__v))");
        sb.AppendLine($"                        tx.AddPropertyValue(id, \"{prop.GraphKey}\", {writeExpr});");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine($"            foreach (var __v in __old)");
        sb.AppendLine($"                tx.RemovePropertyValue(id, \"{prop.GraphKey}\", {writeExpr});");
        sb.AppendLine("        }");
    }
}
