using System.Text;

namespace Quiver.SourceGen;

internal static class GraphNodeEmitter
{
    private static readonly Dictionary<string, (string write, string read)> _typeMap = new()
    {
        ["string"]  = ("PropertyValue.FromString(entity.{0})", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["string?"] = ("PropertyValue.FromString(entity.{0} ?? \"\")", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["int"]     = ("PropertyValue.FromInt32(entity.{0})", "tx.GetProperty(id, \"{1}\").Int32Value"),
        ["long"]    = ("PropertyValue.FromInt64(entity.{0})", "tx.GetProperty(id, \"{1}\").Int64Value"),
        ["double"]  = ("PropertyValue.FromDouble(entity.{0})", "tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["bool"]    = ("PropertyValue.FromBool(entity.{0})", "tx.GetProperty(id, \"{1}\").BoolValue"),
    };

    private static readonly Dictionary<string, string> _indexCallMap = new()
    {
        ["string"]  = "tx.IndexInsert(\"{0}\", entity.{1}, id);",
        ["string?"] = "tx.IndexInsert(\"{0}\", entity.{1} ?? \"\", id);",
        ["int"]     = "tx.IndexInsert(\"{0}\", (long)entity.{1}, id);",
        ["long"]    = "tx.IndexInsert(\"{0}\", entity.{1}, id);",
        ["double"]  = "tx.IndexInsert(\"{0}\", entity.{1}, id);",
    };

    private static readonly Dictionary<string, string> _seekCallMap = new()
    {
        ["string"]  = "Quiver.Operators.LiteralProvider.String(value)",
        ["string?"] = "Quiver.Operators.LiteralProvider.String(value ?? \"\")",
        ["int"]     = "Quiver.Operators.LiteralProvider.Int64((long)value)",
        ["long"]    = "Quiver.Operators.LiteralProvider.Int64(value)",
        ["double"]  = "Quiver.Operators.LiteralProvider.Double(value)",
    };

    // PW-18 follow-up: C# 型から既定の IndexKind を推論するマップ。
    // [GraphIndexed] がここに無い型に付いた場合、EnsureIndexes / CreateIndex 経路は対象外。
    private static readonly Dictionary<string, string> _indexKindMap = new()
    {
        ["string"]  = "Quiver.IndexKind.StringEquality",
        ["string?"] = "Quiver.IndexKind.StringEquality",
        ["int"]     = "Quiver.IndexKind.Int32Equality",
        ["long"]    = "Quiver.IndexKind.Int64Equality",
        ["double"]  = "Quiver.IndexKind.DoubleEquality",
    };

    public static string Emit(GraphNodeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Quiver;");
        sb.AppendLine("using Quiver.Client;");
        sb.AppendLine("using Quiver.Core;");
        sb.AppendLine("using Quiver.Operators;");
        sb.AppendLine("using Quiver.Stores;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var indexedProps = model.Properties.FindAll(p => p.IndexName != null);
        bool hasIndexed  = indexedProps.Count > 0;

        // IGraphNode<T> 実装宣言。PW-18 follow-up: スキーマ宣言用に IGraphNodeSchema<T> も実装する。
        sb.AppendLine($"partial class {model.ClassName} : Quiver.Client.IGraphNode<{model.ClassName}>, Quiver.IGraphNodeSchema<{model.ClassName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string GraphLabel => \"{model.Label}\";");
        sb.AppendLine();

        // Insert
        sb.AppendLine($"    public static Quiver.Core.NodeId Insert(IGraphTransaction tx, {model.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var id = tx.CreateNode(\"{model.Label}\");");
        foreach (var prop in model.Properties)
            EmitSetProperty(sb, prop);
        sb.AppendLine("        return id;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // InsertIndexed — always generated (falls back to Insert when no indexed props)
        sb.AppendLine($"    public static Quiver.Core.NodeId InsertIndexed(IGraphTransaction tx, {model.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        var id = Insert(tx, entity);");
        foreach (var prop in indexedProps)
        {
            if (_indexCallMap.TryGetValue(prop.CSharpType, out var fmt))
                sb.AppendLine($"        {string.Format(fmt, prop.IndexName, prop.PropertyName)}");
        }
        sb.AppendLine("        return id;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Load
        sb.AppendLine($"    public static {model.ClassName} Load(IGraphTransaction tx, Quiver.Core.NodeId id)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.ClassName}");
        sb.AppendLine("        {");
        foreach (var prop in model.Properties)
        {
            if (_typeMap.TryGetValue(prop.CSharpType, out var map))
                sb.AppendLine($"            {prop.PropertyName} = {string.Format(map.read, prop.PropertyName, prop.GraphKey)},");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Update (formerly Save)
        sb.AppendLine($"    public static void Update(IGraphTransaction tx, Quiver.Core.NodeId id, {model.ClassName} entity)");
        sb.AppendLine("    {");
        foreach (var prop in model.Properties)
            EmitSetProperty(sb, prop);
        sb.AppendLine("    }");
        sb.AppendLine();

        // Delete
        sb.AppendLine($"    public static void Delete(IGraphTransaction tx, Quiver.Core.NodeId id) => tx.DeleteNode(id);");

        // PW-18 follow-up: EnsureIndexes — [GraphIndexed] 付き全プロパティ分の CreateIndex を発行
        sb.AppendLine();
        sb.AppendLine("    public static void EnsureIndexes(Quiver.ISchemaApi schema)");
        sb.AppendLine("    {");
        foreach (var prop in indexedProps)
        {
            if (!_indexKindMap.TryGetValue(prop.CSharpType, out var kindExpr)) continue;
            sb.AppendLine(
                $"        schema.CreateIndex(\"{prop.IndexName}\", \"{model.Label}\", \"{prop.GraphKey}\", {kindExpr});");
        }
        sb.AppendLine("    }");

        // PW-18 follow-up: CreateIndex(propertyName, kindOverride?) — 単一プロパティ用
        sb.AppendLine();
        sb.AppendLine("    public static void CreateIndex(Quiver.ISchemaApi schema, string propertyName, Quiver.IndexKind? kindOverride)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (propertyName)");
        sb.AppendLine("        {");
        foreach (var prop in indexedProps)
        {
            if (!_indexKindMap.TryGetValue(prop.CSharpType, out var kindExpr)) continue;
            sb.AppendLine($"            case \"{prop.PropertyName}\":");
            sb.AppendLine(
                $"                schema.CreateIndex(\"{prop.IndexName}\", \"{model.Label}\", \"{prop.GraphKey}\", kindOverride ?? {kindExpr});");
            sb.AppendLine("                return;");
        }
        sb.AppendLine("            default:");
        sb.AppendLine($"                throw new System.ArgumentException(\"'\" + propertyName + \"' は {model.ClassName} で [GraphIndexed] が付与されたプロパティではありません。\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        // FindBy* — one method per [GraphIndexed] property
        foreach (var prop in indexedProps)
        {
            if (!_seekCallMap.TryGetValue(prop.CSharpType, out var seekExpr)) continue;
            var paramType = prop.CSharpType.TrimEnd('?');
            sb.AppendLine();
            sb.AppendLine($"    public static System.Collections.Generic.List<(Quiver.Core.NodeId Id, {model.ClassName} Entity)> FindBy{prop.PropertyName}(");
            sb.AppendLine($"        IGraphTransaction tx, {paramType} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var results = new System.Collections.Generic.List<(Quiver.Core.NodeId, {model.ClassName})>();");
            sb.AppendLine($"        var op = new NodeIndexSeekOperator(\"{prop.IndexName}\", {seekExpr});");
            sb.AppendLine("        using var r = tx.Execute(op);");
            sb.AppendLine("        foreach (var row in r.Rows())");
            sb.AppendLine("        {");
            sb.AppendLine("            var id = row.GetNodeId(0);");
            sb.AppendLine("            results.Add((id, Load(tx, id)));");
            sb.AppendLine("        }");
            sb.AppendLine("        return results;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSetProperty(StringBuilder sb, PropertyModel prop)
    {
        if (!_typeMap.TryGetValue(prop.CSharpType, out var map)) return;
        var writeExpr = string.Format(map.write, prop.PropertyName, prop.GraphKey);
        sb.AppendLine($"        tx.SetProperty(id, \"{prop.GraphKey}\", {writeExpr});");
    }
}
