using System.Runtime.CompilerServices;

// 旧サブアセンブリの統合により InternalsVisibleTo をここへ集約。
// テスト/benchmark と、公開面を狭く保った同梱 add-on の Quiver.Rag に公開する。
[assembly: InternalsVisibleTo("Quiver.Tests")]
[assembly: InternalsVisibleTo("Quiver.Backend.Tests")]
[assembly: InternalsVisibleTo("Quiver.Index.Tests")]
[assembly: InternalsVisibleTo("Quiver.Operators.Tests")]
[assembly: InternalsVisibleTo("Quiver.PropertyTests")]
[assembly: InternalsVisibleTo("Quiver.Storage.Tests")]
[assembly: InternalsVisibleTo("Quiver.Stores.Tests")]
[assembly: InternalsVisibleTo("Quiver.Transactions.Tests")]
[assembly: InternalsVisibleTo("Quiver.Wal.Tests")]
[assembly: InternalsVisibleTo("Quiver.Benchmarks")]
[assembly: InternalsVisibleTo("Quiver.Benchmarks.RecallCheck")]
[assembly: InternalsVisibleTo("Quiver.Rag")]
[assembly: InternalsVisibleTo("Quiver.Hosting")]
[assembly: InternalsVisibleTo("Quiver.OpenTelemetry")]
// 内部実装 (codec / WAL parser / 物理オペレータ) を直接検査する dev/test 系。
[assembly: InternalsVisibleTo("Quiver.Codec.Tests")]
[assembly: InternalsVisibleTo("Quiver.FuzzTests")]
[assembly: InternalsVisibleTo("QuiverSandbox")]
[assembly: InternalsVisibleTo("RagSandbox")]
[assembly: InternalsVisibleTo("Quiver.Mcp")]
[assembly: InternalsVisibleTo("Quiver.SampleDbGen")]
[assembly: InternalsVisibleTo("Quiver.Client.Tests")]
[assembly: InternalsVisibleTo("Quiver.SourceGen.Tests")]
[assembly: InternalsVisibleTo("Quiver.Hosting.Tests")]
[assembly: InternalsVisibleTo("Quiver.Rag.Tests")]
[assembly: InternalsVisibleTo("Quiver.Samples.Crud")]
[assembly: InternalsVisibleTo("Quiver.Samples.Traversal")]
[assembly: InternalsVisibleTo("Quiver.Samples.Match")]
[assembly: InternalsVisibleTo("Quiver.Samples.SourceGen")]
[assembly: InternalsVisibleTo("Quiver.Samples.Vector")]
[assembly: InternalsVisibleTo("Quiver.Samples.Hosting")]
[assembly: InternalsVisibleTo("Quiver.Samples.Observability")]
[assembly: InternalsVisibleTo("Quiver.Samples.Migration")]
[assembly: InternalsVisibleTo("Quiver.Samples.Rag")]
[assembly: InternalsVisibleTo("Quiver.Samples.QueryPatterns")]
[assembly: InternalsVisibleTo("Quiver.Samples.Signal")]
[assembly: InternalsVisibleTo("Quiver.Samples.Nexuses")]
[assembly: InternalsVisibleTo("Quiver.Samples.DirectedNexuses")]
[assembly: InternalsVisibleTo("Quiver.Samples.MinimumHittingSet")]
[assembly: InternalsVisibleTo("Quiver.Samples.PersistenceH0")]
[assembly: InternalsVisibleTo("Quiver.Samples.FormalConcepts")]
[assembly: InternalsVisibleTo("Quiver.Samples.GraphAnnotations")]
