using System.Text;

namespace GraphDb.Engine.Client.SourceGen;

internal static class GraphNodeEmitter
{
    private static readonly Dictionary<string, (string write, string read)> _typeMap = new()
    {
        ["string"]  = ("PropertyValue.FromString(entity.{0})", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["string?"] = ("PropertyValue.FromString(entity.{0} ?? \"\")", "System.Text.Encoding.UTF8.GetString(tx.GetProperty(id, \"{1}\").Utf8StringValue)"),
        ["int"]     = ("PropertyValue.FromInt32(entity.{0})", "tx.GetProperty(id, \"{1}\").Int32Value"),
        ["long"]    = ("PropertyValue.FromInt64(entity.{0})", "tx.GetProperty(id, \"{1}\").Int64Value"),
        ["double"]  = ("PropertyValue.FromDouble(entity.{0})", "tx.GetProperty(id, \"{1}\").DoubleValue"),
        ["bool"]    = ("PropertyValue.FromBool(entity.{0})", "tx.GetProperty(id, \"{1}\").BoolValue"),
    };

    private static readonly Dictionary<string, string> _indexCallMap = new()
    {
        ["string"]  = "tx.IndexInsert(\"{0}\", entity.{1}, id);",
        ["string?"] = "tx.IndexInsert(\"{0}\", entity.{1} ?? \"\", id);",
        ["int"]     = "tx.IndexInsert(\"{0}\", (long)entity.{1}, id);",
        ["long"]    = "tx.IndexInsert(\"{0}\", entity.{1}, id);",
        ["double"]  = "tx.IndexInsert(\"{0}\", entity.{1}, id);",
    };

    private static readonly Dictionary<string, string> _seekCallMap = new()
    {
        ["string"]  = "GraphDb.Engine.Operators.LiteralProvider.String(value)",
        ["string?"] = "GraphDb.Engine.Operators.LiteralProvider.String(value ?? \"\")",
        ["int"]     = "GraphDb.Engine.Operators.LiteralProvider.Int64((long)value)",
        ["long"]    = "GraphDb.Engine.Operators.LiteralProvider.Int64(value)",
        ["double"]  = "GraphDb.Engine.Operators.LiteralProvider.Double(value)",
    };

    public static string Emit(GraphNodeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using GraphDb.Engine;");
        sb.AppendLine("using GraphDb.Engine.Client;");
        sb.AppendLine("using GraphDb.Engine.Core;");
        sb.AppendLine("using GraphDb.Engine.Operators;");
        sb.AppendLine("using GraphDb.Engine.Stores;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var indexedProps = model.Properties.FindAll(p => p.IndexName != null);
        bool hasIndexed  = indexedProps.Count > 0;

        // IGraphNode<T> 実装宣言
        sb.AppendLine($"partial class {model.ClassName} : GraphDb.Engine.Client.IGraphNode<{model.ClassName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string GraphLabel => \"{model.Label}\";");
        sb.AppendLine();

        // Insert
        sb.AppendLine($"    public static GraphDb.Engine.Core.NodeId Insert(IGraphTransaction tx, {model.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var id = tx.CreateNode(\"{model.Label}\");");
        foreach (var prop in model.Properties)
            EmitSetProperty(sb, prop);
        sb.AppendLine("        return id;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // InsertIndexed — always generated (falls back to Insert when no indexed props)
        sb.AppendLine($"    public static GraphDb.Engine.Core.NodeId InsertIndexed(IGraphTransaction tx, {model.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        var id = Insert(tx, entity);");
        foreach (var prop in indexedProps)
        {
            if (_indexCallMap.TryGetValue(prop.CSharpType, out var fmt))
                sb.AppendLine($"        {string.Format(fmt, prop.IndexName, prop.PropertyName)}");
        }
        sb.AppendLine("        return id;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Load
        sb.AppendLine($"    public static {model.ClassName} Load(IGraphTransaction tx, GraphDb.Engine.Core.NodeId id)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.ClassName}");
        sb.AppendLine("        {");
        foreach (var prop in model.Properties)
        {
            if (_typeMap.TryGetValue(prop.CSharpType, out var map))
                sb.AppendLine($"            {prop.PropertyName} = {string.Format(map.read, prop.PropertyName, prop.GraphKey)},");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Update (formerly Save)
        sb.AppendLine($"    public static void Update(IGraphTransaction tx, GraphDb.Engine.Core.NodeId id, {model.ClassName} entity)");
        sb.AppendLine("    {");
        foreach (var prop in model.Properties)
            EmitSetProperty(sb, prop);
        sb.AppendLine("    }");
        sb.AppendLine();

        // Delete
        sb.AppendLine($"    public static void Delete(IGraphTransaction tx, GraphDb.Engine.Core.NodeId id) => tx.DeleteNode(id);");

        // FindBy* — one method per [GraphIndexed] property
        foreach (var prop in indexedProps)
        {
            if (!_seekCallMap.TryGetValue(prop.CSharpType, out var seekExpr)) continue;
            var paramType = prop.CSharpType.TrimEnd('?');
            sb.AppendLine();
            sb.AppendLine($"    public static System.Collections.Generic.List<(GraphDb.Engine.Core.NodeId Id, {model.ClassName} Entity)> FindBy{prop.PropertyName}(");
            sb.AppendLine($"        IGraphTransaction tx, {paramType} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var results = new System.Collections.Generic.List<(GraphDb.Engine.Core.NodeId, {model.ClassName})>();");
            sb.AppendLine($"        var op = new NodeIndexSeekOperator(\"{prop.IndexName}\", {seekExpr});");
            sb.AppendLine("        using var r = tx.Execute(op);");
            sb.AppendLine("        foreach (var row in r.Rows())");
            sb.AppendLine("        {");
            sb.AppendLine("            var id = row.GetNodeId(0);");
            sb.AppendLine("            results.Add((id, Load(tx, id)));");
            sb.AppendLine("        }");
            sb.AppendLine("        return results;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSetProperty(StringBuilder sb, PropertyModel prop)
    {
        if (!_typeMap.TryGetValue(prop.CSharpType, out var map)) return;
        var writeExpr = string.Format(map.write, prop.PropertyName, prop.GraphKey);
        sb.AppendLine($"        tx.SetProperty(id, \"{prop.GraphKey}\", {writeExpr});");
    }
}
