param(
    [string]$OutputPath = "docs/generated/architecture.md"
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$solutionPath = Join-Path $repoRoot "Yatagarasu.slnx"
$outputFullPath = [IO.Path]::GetFullPath((Join-Path $repoRoot $OutputPath))
$docsRoot = [IO.Path]::GetFullPath((Join-Path $repoRoot "docs/generated"))

if (-not $outputFullPath.StartsWith($docsRoot + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Output path must remain under docs/generated: $outputFullPath"
}

[xml]$solution = Get-Content -LiteralPath $solutionPath -Raw -Encoding UTF8
$projectPaths = @(
    $solution.SelectNodes("//Project") |
        ForEach-Object { $_.Path.Replace("/", [IO.Path]::DirectorySeparatorChar) } |
        Sort-Object
)

$projects = foreach ($projectPath in $projectPaths) {
    $fullPath = Join-Path $repoRoot $projectPath
    [xml]$projectXml = Get-Content -LiteralPath $fullPath -Raw -Encoding UTF8
    $references = @(
        $projectXml.SelectNodes("//ProjectReference") |
            ForEach-Object {
                $referencePath = [IO.Path]::GetFullPath((Join-Path (Split-Path $fullPath) $_.Include))
                [IO.Path]::GetFileNameWithoutExtension($referencePath)
            } |
            Sort-Object -Unique
    )
    $packages = @(
        $projectXml.SelectNodes("//PackageReference") |
            ForEach-Object { $_.Include } |
            Sort-Object -Unique
    )

    [PSCustomObject]@{
        Name = [IO.Path]::GetFileNameWithoutExtension($projectPath)
        Path = $projectPath.Replace([IO.Path]::DirectorySeparatorChar, "/")
        Group = ($projectPath -split "[\\/]")[0]
        References = $references
        Packages = $packages
    }
}

$productionProjects = @($projects | Where-Object { $_.Group -in @("src", "tools") } | Sort-Object Group, Name)
$namespaceCounts = @{}

Get-ChildItem -LiteralPath (Join-Path $repoRoot "src") -Recurse -File -Filter "*.cs" |
    Where-Object { $_.FullName -notmatch "[\\/](bin|obj)[\\/]" } |
    ForEach-Object {
        $match = Select-String -LiteralPath $_.FullName -Pattern "^\s*namespace\s+([^;{]+)" -Encoding UTF8 | Select-Object -First 1
        if ($match) {
            $namespace = $match.Matches[0].Groups[1].Value.Trim()
            if (-not $namespaceCounts.ContainsKey($namespace)) {
                $namespaceCounts[$namespace] = 0
            }
            $namespaceCounts[$namespace]++
        }
    }

$lines = [Collections.Generic.List[string]]::new()
$lines.Add("<!-- Generated by scripts/generate-docs.ps1. Do not edit. -->")
$lines.Add("")
$lines.Add("# Generated architecture inventory")
$lines.Add("")
$lines.Add('This document is generated from `Yatagarasu.slnx`, project files, and source namespace declarations.')
$lines.Add("")
$lines.Add("## Production projects")
$lines.Add("")
$lines.Add("| Project | Group | Path | Direct project references | External packages |")
$lines.Add("|---|---|---|---|---|")

foreach ($project in $productionProjects) {
    $references = if ($project.References.Count -eq 0) { "None" } else { ($project.References | ForEach-Object { '`{0}`' -f $_ }) -join ", " }
    $packages = if ($project.Packages.Count -eq 0) { "None" } else { ($project.Packages | ForEach-Object { '`{0}`' -f $_ }) -join ", " }
    $lines.Add(('| `{0}` | {1} | `{2}` | {3} | {4} |' -f $project.Name, $project.Group, $project.Path, $references, $packages))
}

$lines.Add("")
$lines.Add("## Project dependency graph")
$lines.Add("")
$lines.Add('```mermaid')
$lines.Add("flowchart LR")

foreach ($project in $productionProjects) {
    $projectId = $project.Name -replace "[^A-Za-z0-9_]", "_"
    $lines.Add("    $projectId[`"$($project.Name)`"]")
}

foreach ($project in $productionProjects) {
    $sourceId = $project.Name -replace "[^A-Za-z0-9_]", "_"
    foreach ($reference in $project.References) {
        $target = $productionProjects | Where-Object Name -eq $reference | Select-Object -First 1
        if ($target) {
            $targetId = $target.Name -replace "[^A-Za-z0-9_]", "_"
            $lines.Add("    $sourceId --> $targetId")
        }
    }
}

$lines.Add('```')
$lines.Add("")
$lines.Add("## Source namespaces")
$lines.Add("")
$lines.Add("| Namespace | C# files |")
$lines.Add("|---|---:|")

foreach ($entry in $namespaceCounts.GetEnumerator() | Sort-Object Name) {
    $lines.Add(('| `{0}` | {1} |' -f $entry.Name, $entry.Value))
}

New-Item -ItemType Directory -Path (Split-Path $outputFullPath) -Force | Out-Null
[IO.File]::WriteAllLines($outputFullPath, $lines, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $OutputPath"
