using System.Runtime.CompilerServices;

// 旧サブアセンブリの統合により InternalsVisibleTo をここへ集約。
// テスト/benchmark と、公開面を狭く保った同梱 add-on の Yatagarasu.Rag に公開する。
[assembly: InternalsVisibleTo("Yatagarasu.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Backend.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Index.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Operators.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.PropertyTests")]
[assembly: InternalsVisibleTo("Yatagarasu.Storage.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Stores.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Transactions.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Wal.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Benchmarks")]
[assembly: InternalsVisibleTo("Yatagarasu.Benchmarks.RecallCheck")]
[assembly: InternalsVisibleTo("Yatagarasu.Rag")]
[assembly: InternalsVisibleTo("Yatagarasu.Hosting")]
[assembly: InternalsVisibleTo("Yatagarasu.OpenTelemetry")]
// 内部実装 (codec / WAL parser / 物理オペレータ) を直接検査する dev/test 系。
[assembly: InternalsVisibleTo("Yatagarasu.Codec.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.FuzzTests")]
[assembly: InternalsVisibleTo("YatagarasuSandbox")]
[assembly: InternalsVisibleTo("RagSandbox")]
[assembly: InternalsVisibleTo("Yatagarasu.Mcp")]
[assembly: InternalsVisibleTo("Yatagarasu.SampleDbGen")]
[assembly: InternalsVisibleTo("Yatagarasu.Client.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.SourceGen.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Hosting.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Rag.Tests")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Crud")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Traversal")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Match")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.SourceGen")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Vector")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Hosting")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Observability")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Migration")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Rag")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.QueryPatterns")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Signal")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.Nexuses")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.DirectedNexuses")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.MinimumHittingSet")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.PersistenceH0")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.FormalConcepts")]
[assembly: InternalsVisibleTo("Yatagarasu.Samples.GraphAnnotations")]
